Updated readme to match updated readme template.
usdot-jpo-codehub/codehub-ui pull request #163
Opened 2020-07-20 15:32 UTC by mary-vandyke

2020-07-21 17:51 UTC, nickpricedev requested changes
A few formatting changes requested. Overall content looks good.

2020-07-21 17:51 UTC, nickprice-bah commented on README.md
>  Labor Hours: 0
Were these copied in by mistake?

2020-07-21 17:51 UTC, nickprice-bah commented on README.md
> +Please read CONTRIBUTING.md for details on our Code of Conduct, the process for submitting pull requests to us, and how contributions will be released.
This should include a hyperlink to the CONTRIBUTING.md file

2020-07-21 17:51 UTC, nickprice-bah commented on README.md
>  This project is licensed under the Apache 2.0 License.
This should include a hyperlink to the LICENSE file

2020-07-21 17:51 UTC, nickprice-bah commented on README.md
> +- Rename Insight page to Metrics.
This should include a hyperlink to a CHANGELOG.md file.

2020-07-21 17:51 UTC, nickprice-bah commented on README.md
> -Please contribute to this repository using GitHub Pull Requests and GitHub Issues.
This should include a hyperlink to a CONTRIBUTING.md file

2020-07-21 17:51 UTC, nickprice-bah commented on README.md
Not a requirement of the README template, but consider adding Codebuild badge?

2020-07-23 18:53 UTC, nickpricedev approved these changes

2020-07-23 18:54 UTC, merged